name: flutter_window_title_issue
description: https://github.com/canonical/ubuntu-desktop-installer/issues/670
publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^4.1.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
